#!/bin/bash

echo -e "\033[1;4;93m\techo /usr/lib/*ck* Two wildcards in one directory)\033[0m"

input_str=$'echo /usr/lib/*ck*'
diff <(/bin/sh <<< "$input_str" 2>&1) <(../shell <<< "$input_str" 2>&1)
exit $?
