#!/bin/bash

rm -f out1 out2
echo -e "\033[1;4;93m\tOutput redirection\033[0m"

sh_in=$'ls files > out1'
shell_in=$'ls files > out2'
diff <(/bin/sh <<< "$sh_in" 2>&1; cat out1) <(../shell <<< "$shell_in" 2>&1 ; cat out2)
exit $?
