#!/bin/bash

rm -f shell-in sh-in

echo -e "\033[1;4;93m\ttest source\033[0m"

echo -e "echo \"You Win!\"" > shell-in
echo -e "echo \"You Win!\"" > sh-in

shell_input=$'source shell-in'
bash_input=$'source sh-in'

diff <(/bin/bash <<< "$bash_input" 2>&1) <(../shell <<< "$shell_input" 2>&1)
exit $?
