#!/bin/bash

rm -f sh-out shell-out shell-in sh-in

echo -e "\033[1;4;93mTest_subshell: test subshell\033[0m"


echo "ls test3* > file-list " > shell-in
echo 'ls -al $(cat file-list) ' >> shell-in
../shell < shell-in > shell-out

echo "ls test3* > file-list" > sh-in
echo 'ls -al $(cat file-list) ' >> sh-in
/bin/sh < sh-in > sh-out

diff sh-out shell-out > /dev/null 2>&1
exit $?
