#! /bin/bash

echo -e "\033[1;4;93m\tEnvironment Variable Expansion - \${_}\033[0m"

# should not grab redirects
input_str=$'ls > /dev/null\necho ${_}'
diff <(echo "ls") <(../shell <<< "$input_str" 2>&1)
if [ $? -ne 0 ]; then
  exit -1
fi

# should grab arguments
input_str=$'ls -al > /dev/null\necho ${_}'
diff <(echo "-al") <(../shell <<< "$input_str" 2>&1)
if [ $? -ne 0 ]; then
  exit -1
fi
exit $?
